config/routes.rb
Rails.application.routes.draw do
  resources :bmis

end

app/models/bmi.rb
class Bmi < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bmis_controller.rb
class BmisController < ApplicationController
  before_action :set_bmi, only: [:show, :edit, :update, :destroy]

  # GET /bmis
  # GET /bmis.json
  def index
    @bmis = Bmi.all
  end

  # GET /bmis/1
  # GET /bmis/1.json
  def show
  end

  # GET /bmis/new
  def new
    @bmi = Bmi.new
  end

  # GET /bmis/1/edit
  def edit
  end

  # POST /bmis
  # POST /bmis.json
  def create
    @bmi = Bmi.new(bmi_params)

    respond_to do |format|
      if @bmi.save
        format.html { redirect_to @bmi, notice: 'Bmi was successfully created.' }
        format.json { render :show, status: :created, location: @bmi }
      else
        format.html { render :new }
        format.json { render json: @bmi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bmis/1
  # PATCH/PUT /bmis/1.json
  def update
    respond_to do |format|
      if @bmi.update(bmi_params)
        format.html { redirect_to @bmi, notice: 'Bmi was successfully updated.' }
        format.json { render :show, status: :ok, location: @bmi }
      else
        format.html { render :edit }
        format.json { render json: @bmi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bmis/1
  # DELETE /bmis/1.json
  def destroy
    @bmi.destroy
    respond_to do |format|
      format.html { redirect_to bmis_url, notice: 'Bmi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bmi
      @bmi = Bmi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bmi_params
      params.require(:bmi).permit(:name, :height, :weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmis_helper.rb
module BmisHelper
end

app/views/bmis/_bmi.html.erb
<tr>
    <td><%= bmi.name %></td>
    <td><%= bmi.height %></td>
    <td><%= bmi.weight %></td>
    <td>
    	  <i><%= (bmi.weight/(bmi.height * bmi.height)).round(2) %></i>
    </td>
    <td><%= link_to 'Show', bmi %></td>
    <td><%= link_to 'Edit', edit_bmi_path(bmi) %></td>
    <td><%= link_to 'Destroy', bmi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/bmis/_form.html.erb
<%= form_for(@bmi) do |f| %>
  <% if @bmi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bmi.errors.count, "error") %> prohibited this bmi from being saved:</h2>

      <ul>
      <% @bmi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bmis/create.html.erb
name:<%= params[:name] %>
height:<%= params[:height] %>
weight:<%= params[:weight] %>
<%= link_to 'Show', @bmi %> |
<%= link_to 'Back', bmis_path %>

app/views/bmis/edit.html.erb
<h1>Editing bmi</h1>

<%= render 'form' %>

<%= link_to 'Show', @bmi %> |
<%= link_to 'Back', bmis_path %>

app/views/bmis/index.html.erb
<h1>Listing BMI</h1>
<p id="notice"><%= flash[:notice] %></p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Weight</th>
      <th>BMI</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%=render partial: 'bmi' ,collection: @bmis, as: :bmi %>
  </tbody>
</table>


<br>

<%= link_to 'New Bmi', new_bmi_path %>

app/views/bmis/new.html.erb
<h1>New bmi</h1>

<%= render 'form' %>

<%= link_to 'Back', bmis_path %>

app/views/bmis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bmi.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @bmi.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @bmi.weight %>
</p>


<%= link_to 'Edit', edit_bmi_path(@bmi) %> |
<%= link_to 'Back', bmis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calbmi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>